# Based on https://github.com/squidfunk/mkdocs-material/blob/master/.github/workflows/ci.yml

name: CI

# Controls when the action will run.
on:
  push:
    branches:
      - mkdocs-material
  pull_request:
    branches:
      - mkdocs-material

env:
  CI: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    if: github.event != 'pull_request' && github.ref == 'refs/heads/mkdocs-material'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build documentation
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs gh-deploy --force
          mkdocs --version
          pip show mkdocs-material
